import styles from "./page.module.css";

const services = [
  ["01", "Wypełnienie SAQ", "Dobieramy właściwy typ ankiety samooceny i przechodzimy przez nią wspólnie."],
  ["02", "Przygotowanie dokumentacji", "Tworzymy polityki, procedury i dowody wymagane przez standard."],
  ["03", "Koordynacja skanów ASV", "Pomagamy zorganizować skan, zrozumieć wynik i usunąć wykryte luki."],
  ["04", "Utrzymanie zgodności", "Pilnujemy terminów, odświeżamy dokumentację i wspieramy Cię w kolejnych latach."],
];

function CardIcon() { return <svg viewBox="0 0 72 52" aria-hidden="true"><rect x="1.5" y="9" width="55" height="37" rx="6" fill="#17636F"/><rect x="8" y="17" width="11" height="8" rx="2" fill="#7FC7D2"/><rect x="8" y="35" width="24" height="3" rx="1.5" fill="#ffffff66"/><rect x="8" y="40.5" width="16" height="3" rx="1.5" fill="#ffffff40"/><path d="M40 30.5 46.5 37 66 12" fill="none" stroke="#fff" strokeWidth="9" strokeLinecap="round" strokeLinejoin="round"/><path d="M40 30.5 46.5 37 66 12" fill="none" stroke="#46B24E" strokeWidth="5.5" strokeLinecap="round" strokeLinejoin="round"/></svg>; }
function Brand() { return <a className={styles.brand} href="#top"><span className={styles.brandMark}><CardIcon /></span><span><b>123</b>PCI</span></a>; }
function Flag({ language, href, active }: { language: "pl" | "en" | "de"; href: string; active?: boolean }) { const shapes = language === "pl" ? <><rect width="24" height="8" fill="#fff"/><rect y="8" width="24" height="8" fill="#DC143C"/></> : language === "en" ? <><rect width="24" height="16" fill="#012169"/><path d="M0 0 24 16M24 0 0 16" stroke="#fff" strokeWidth="3.2"/><path d="M0 0 24 16M24 0 0 16" stroke="#C8102E" strokeWidth="1.6"/><path d="M12 0V16M0 8H24" stroke="#fff" strokeWidth="5"/><path d="M12 0V16M0 8H24" stroke="#C8102E" strokeWidth="3"/></> : <><rect width="24" height="5.34" fill="#000"/><rect y="5.34" width="24" height="5.33" fill="#DD0000"/><rect y="10.67" width="24" height="5.33" fill="#FFCE00"/></>; return <a className={`${styles.flag} ${active ? styles.flagActive : ""}`} href={href} aria-label={language === "pl" ? "Polski" : language === "en" ? "English" : "Deutsch"}><svg viewBox="0 0 24 16" aria-hidden="true">{shapes}</svg></a>; }

export default function Home() {
  return <main id="top">
    <header className={styles.header}><nav className={styles.nav}><Brand /><div className={styles.links}><a href="#dla-kogo">Dla kogo</a><a href="#uslugi">Usługi</a><a href="#jak-to-dziala">Jak to działa</a></div><div className={styles.languages}><Flag language="pl" href="/" active /><Flag language="en" href="/en" /><Flag language="de" href="/de" /></div><a className={styles.navCta} href="#kontakt">Skontaktuj się</a></nav></header>
    <section className={styles.hero}><div className={styles.heroGrid}><div><p className={styles.badge}>● Zgodność z PCI DSS v4.0</p><h1>PCI DSS Compliance – <em>wspieramy</em> w procesie osiągnięcia zgodności.</h1><p className={styles.lead}>Pomagamy małym merchantom oraz biurom turystycznym IATA bezpiecznie przetwarzać dane kart i spełnić wymogi PCI DSS - bez żargonu, bez chaosu, z jasnym planem działania.</p><div className={styles.actions}><a className={styles.primary} href="#kontakt">Skontaktuj się →</a><a className={styles.secondary} href="#uslugi">Zobacz usługi</a></div><div className={styles.chips}><span>SAQ A / A-EP / D</span><span>Skany ASV</span><span>Biura IATA</span><span>PL · EN · DE</span></div></div><aside className={styles.progress}><div className={styles.progressHeading}><CardIcon /><div><p className={styles.eyebrow}>TWOJA DROGA DO ZGODNOŚCI</p><h2>Trzy proste etapy</h2></div></div><div className={styles.progressSteps}>{["Określenie zakresu", "Zebranie danych", "Przygotowanie dokumentacji"].map((step) => <p className={styles.progressStep} key={step}><span>✓</span>{step}</p>)}</div></aside></div></section>
    <section id="dla-kogo" className={styles.audience}><p className={styles.kicker}>DLA KOGO</p><h2>Stworzone dla tych, którzy przyjmują płatności kartą.</h2><div className={styles.audienceCards}><article className={styles.iata}><span>WYRÓŻNIONE</span><h3>Biura turystyczne IATA</h3><p>Rozliczenia BSP i IATA oznaczają realne przetwarzanie danych kart. Pomagamy przejść przez PCI DSS bez zatrzymywania sprzedaży.</p><p><b>Oferta dla członków IATA.</b> Pierwszy rok gratis. Kolejny 400 PLN netto<sup>*</sup></p><small>* Dotyczy biur turystycznych, obsługa SAQ CVT.</small><div>Rozliczenia BSP / IATA · GDS · Płatności online i stacjonarne</div></article><article className={styles.merchants}><h3>Mali merchanci</h3><p>Sklepy internetowe i stacjonarne, usługodawcy oraz subskrypcje.</p><ul><li>✓ E-commerce z bramką płatniczą</li><li>✓ Terminale i płatności stacjonarne</li><li>✓ Firmy bez własnego IT/security</li></ul></article></div></section>
    <section id="uslugi" className={styles.services}><div className={styles.sectionHead}><div><p className={styles.kicker}>USŁUGI</p><h2>Wszystko, czego potrzebujesz do zgodności.</h2></div><a href="#kontakt">Porozmawiajmy o zakresie →</a></div><div className={styles.serviceGrid}>{services.map(([n,t,d]) => <article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
    <section id="jak-to-dziala" className={styles.steps}><p className={styles.kicker}>JAK TO DZIAŁA</p><h2>Cztery kroki. Resztę robimy my.</h2><p className={styles.sectionLead}>Kontaktujesz się z nami, a dalej prowadzimy Cię przez cały proces.</p><div className={styles.stepGrid}>{[["01","Kontakt"],["02","Rozmowa"],["03","Zakres"],["04","Dokumentacja"]].map(([n,t]) => <article key={n}><span>{n}</span><h3>{t}</h3><p>Jasny kolejny krok, bez zbędnych formalności.</p></article>)}</div><div className={styles.offer}><b>Oferta dla członków IATA. Pierwszy rok gratis. Kolejny 400 PLN netto<sup>*</sup></b><span>* Dotyczy biur turystycznych, obsługa SAQ CVT.</span></div></section>
    <section id="kontakt" className={styles.contact}><div><p className={styles.kicker}>KONTAKT</p><h2>Zróbmy pierwszy krok razem.</h2><p className={styles.sectionLead}>Zostaw dane, a odezwiemy się z bezpłatną, wstępną oceną zakresu PCI DSS.</p><address className={styles.contactDetails}><a className={styles.contactItem} href="mailto:rluczak@123pci.pl"><span className={styles.contactIcon}>✉</span><span><small>E-mail</small>rluczak@123pci.pl</span></a><a className={styles.contactItem} href="tel:+48500879090"><span className={styles.contactIcon}>☎</span><span><small>Telefon</small>500 87 90 90</span></a></address></div><form className={styles.form} action="/api/contact" method="post"><h3>Wyślij zgłoszenie</h3><input name="website" tabIndex={-1} autoComplete="off" aria-hidden="true" style={{position:"absolute",left:"-9999px"}} /><div className={styles.formRow}><label>Imię i nazwisko<input required name="name" /></label><label>Firma<input required name="company" /></label></div><div className={styles.formRow}><label>E-mail<input required name="email" type="email" /></label><label>Telefon<input name="phone" type="tel" /></label></div><label>Rodzaj działalności<select name="business"><option>Biuro turystyczne (IATA)</option><option>Sklep internetowy</option><option>Handel stacjonarny / terminal</option><option>Inna działalność</option></select></label><label>Wiadomość<textarea name="message" rows={3} /></label><label className={styles.check}><input required type="checkbox" />Zapoznałem/-am się z <a href="/polityka-prywatnosci">polityką prywatności</a> i zgadzam się na kontakt.</label><button type="submit">Wyślij zgłoszenie →</button><small>Odpowiadamy zwykle w ciągu jednego dnia roboczego.</small></form></section>
    <footer className={styles.footer}><Brand /><p>Praktyczne wsparcie w uzyskaniu i utrzymaniu zgodności z PCI DSS.</p><div><a href="/polityka-prywatnosci">Polityka prywatności</a><a href="/cookies">Cookies</a></div><small>© 2026 123PCI. Wszelkie prawa zastrzeżone.</small></footer>
  </main>;
}
